"use client";
import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";

const Label=({children}:{children:React.ReactNode})=><span className="technical-label">{children}</span>;
function CodeScene(){return <div className="journey-code"><div className="window-bar"><i/><i/><i/><span>qorvex / product.ts</span></div><div className="code-body">{["const idea = await discover(ambition);","const system = architect({ idea, scale: true });","const product = build(system, experience);","await deploy(product, { confidence: 0.99 });"].map((x,i)=><div key={x}><span>0{i+1}</span><code>{x}</code></div>)}<div className="code-cursor"/></div><Label>BUILD / ACTIVE</Label></div>}
function ProductScene(){return <div className="product-frame"><div className="product-top"><strong>QX / CONTROL</strong><div className="product-search">Search systems...</div><i/></div><div className="product-shell"><aside><b>Overview</b><span>Projects</span><span>Analytics</span><span>Automations</span><span>Settings</span></aside><div className="product-main"><div className="product-welcome"><div><small>OPERATIONAL OVERVIEW</small><h3>Good morning, Maya.</h3></div><button>New project +</button></div><div className="metric-grid"><div><small>Active systems</small><strong>24</strong><em>+ 12.4%</em></div><div><small>Deployments</small><strong>186</strong><em>All healthy</em></div><div><small>Efficiency</small><strong>94%</strong><em>+ 8.7%</em></div></div><div className="chart-panel"><div><small>SYSTEM ACTIVITY</small><b>Last 30 days</b></div><div className="chart-lines"><i/><i/><i/><i/><i/><i/><span/></div></div><div className="table-panel"><span>Northstar Portal</span><b>Production</b><em>99.99%</em><span>Qorvex AI</span><b>Testing</b><em>87.40%</em></div></div></div><Label>DATABASE / CONNECTED</Label><Label>API / ONLINE</Label></div>}
function CampaignScene(){return <div className="campaign-studio"><div className="studio-head"><Label>CAMPAIGN / 001</Label><span>00:18:24</span><b>LIVE FRAME</b></div><div className="studio-stage"><div className="crop c-tl"/><div className="crop c-tr"/><div className="crop c-bl"/><div className="crop c-br"/><div className="campaign-phone"><small>MOVE WITH</small><strong>INTENT.</strong><i/></div><div className="asset asset-a"><span>POST / 01</span><b>Build momentum.</b></div><div className="asset asset-b"><span>STORY / 02</span><b>QX</b></div><div className="tracking-point p1"/><div className="tracking-point p2"/></div><div className="edit-timeline"><span/><i/><i/><i/><b/></div></div>}
function DataScene(){return <div className="data-room"><div className="data-head"><Label>ILLUSTRATIVE DATA / LIVE</Label><span>CREATIVITY → DATA → GROWTH</span></div><div className="data-kpis"><div><small>ENGAGEMENT</small><strong>48.2K</strong><em>illustrative</em></div><div><small>CTR</small><strong>4.82%</strong><em>demo metric</em></div><div><small>CONVERSIONS</small><strong>2,418</strong><em>sample data</em></div></div><div className="growth-chart"><div className="chart-grid"/><div className="growth-area"/><div className="growth-line"/><i className="g1"/><i className="g2"/><i className="g3"/></div></div>}
export function HeroConsole(){return null}

export default function CinematicJourney(){
 const ref=useRef<HTMLElement>(null);const {scrollYProgress:p}=useScroll({target:ref,offset:["start start","end end"]});
 const codeO=useTransform(p,[0,.04,.2,.3],[0,1,1,0]),codeS=useTransform(p,[0,.22,.31],[.88,1,.74]);
 const productO=useTransform(p,[.22,.32,.52,.61],[0,1,1,0]),productS=useTransform(p,[.22,.37,.56],[.7,1,1.08]);
 const campaignO=useTransform(p,[.54,.64,.76,.84],[0,1,1,0]),dataO=useTransform(p,[.78,.87,1],[0,1,1]),dataS=useTransform(p,[.78,1],[.88,1]);
 const progress=useTransform(p,[0,1],[0,1]);
 const titles=[useTransform(p,[0,.05,.26,.32],[0,1,1,0]),useTransform(p,[.26,.34,.55,.61],[0,1,1,0]),useTransform(p,[.56,.64,.78,.84],[0,1,1,0]),useTransform(p,[.8,.88,1],[0,1,1])];
 return <section ref={ref} className="cinematic-journey" aria-label="From idea to growth"><div className="journey-sticky"><div className="journey-header"><Label>THE QORVEX SYSTEM</Label><div className="journey-progress"><motion.i style={{scaleY:progress}}/></div><span>SCROLL / SCRUB</span></div><div className="journey-title">{["IDEA → CODE","CODE → PRODUCT","PRODUCT → CAMPAIGN","DATA → GROWTH"].map((t,i)=><motion.span key={t} style={{opacity:titles[i]}}>{t}</motion.span>)}</div><motion.div className="journey-scene" style={{opacity:codeO,scale:codeS}}><CodeScene/></motion.div><motion.div className="journey-scene" style={{opacity:productO,scale:productS}}><ProductScene/></motion.div><motion.div className="journey-scene" style={{opacity:campaignO}}><CampaignScene/></motion.div><motion.div className="journey-scene" style={{opacity:dataO,scale:dataS}}><DataScene/></motion.div><div className="journey-footer">{["IDEA","STRATEGY","CODE","PRODUCT","CAMPAIGN","DATA","GROWTH"].map(x=><span key={x}>{x}</span>)}</div></div></section>
}

const factory=[{n:"01",name:"IDEA",copy:"A single signal becomes a direction.",visual:"factory-dot"},{n:"02",name:"STRATEGY",copy:"Research becomes a deliberate system.",visual:"factory-grid"},{n:"03",name:"DESIGN",copy:"The system becomes an experience.",visual:"factory-ui"},{n:"04",name:"DEVELOP",copy:"Every interaction becomes working code.",visual:"factory-code"},{n:"05",name:"LAUNCH",copy:"Tested, deployed and ready for reality.",visual:"factory-launch"},{n:"06",name:"GROWTH",copy:"Attention becomes measurable momentum.",visual:"factory-growth"}];
export function FactoryRail(){const ref=useRef<HTMLElement>(null);const {scrollYProgress:p}=useScroll({target:ref,offset:["start start","end end"]});const x=useTransform(p,[0,1],["0%","-74%"]);return <section ref={ref} className="factory-section"><div className="factory-sticky"><div className="factory-heading"><Label>DIGITAL FACTORY / 06 STAGES</Label><h2>One continuous<br/><em>production line.</em></h2></div><motion.div className="factory-rail" style={{x}}>{factory.map(f=><article key={f.n}><span>{f.n}</span><div className={`factory-visual ${f.visual}`}><i/><i/><i/><i/></div><h3>{f.name}</h3><p>{f.copy}</p></article>)}</motion.div><div className="factory-track"><motion.i style={{scaleX:p}}/></div></div></section>}
