"use client";
import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import { ArrowDown, ArrowRight, ArrowUpRight, Mail, MapPin, Menu, Phone, Plus, X } from "lucide-react";
import dynamic from "next/dynamic";
import Lenis from "lenis";
import CinematicJourney, { FactoryRail, HeroConsole } from "./components/CinematicJourney";

const AmbientScene=dynamic(()=>import("./components/AmbientScene"),{ssr:false});
const services=[["01","Web Development","Corporate websites, custom platforms and scalable web applications."],["02","Mobile Apps","High-performance Android and iOS experiences built for real users."],["03","SaaS Development","Purpose-built products that turn ambitious ideas into recurring value."],["04","AI Automation","Intelligent agents and workflows that remove friction from your business."],["05","Digital Marketing","Performance campaigns engineered around measurable, sustainable growth."],["06","Brand & Design","Identity, product design and creative systems with a singular point of view."],["07","Cloud & DevOps","Resilient infrastructure, deployment and scalable cloud architecture."],["08","Social Growth","Strategy, content systems and management that build lasting attention."]];
const work=[["VANTAGE / REAL ESTATE","A digital property platform built to turn discovery into decision.","Product design · Development","01"],["NEXUS / HEALTHCARE","One connected system for modern clinical operations.","Strategy · SaaS · Cloud","02"],["ARC / COMMERCE","A growth engine that made every interaction measurable.","Commerce · Performance","03"]];
const process=[["01","Discover","We find the real problem, define success and align on direction."],["02","Strategize","We turn research into an intentional product and growth system."],["03","Design","We shape the experience and visual language around your ambition."],["04","Build","We engineer with modern technology and scalable foundations."],["05","Launch","We test, refine and release with confidence—not crossed fingers."],["06","Grow","We learn from reality, optimize performance and compound what works."]];
const tech=["NEXT.JS","REACT","NODE.JS","POSTGRESQL","AWS","DOCKER","OPENAI","SHOPIFY","THREE.JS"];
function Mark(){return <span className="brand-mark">QX</span>}
function Reveal({children,className=""}:{children:React.ReactNode,className?:string}){return <motion.div className={`reveal ${className}`} initial={{opacity:0,y:48,scale:.97,filter:"blur(7px)"}} whileInView={{opacity:1,y:0,scale:1,filter:"blur(0px)"}} viewport={{once:true,margin:"-10%"}} transition={{duration:.95,ease:[.16,1,.3,1]}}>{children}</motion.div>}

export default function Home(){
 const [intro,setIntro]=useState(false),[menu,setMenu]=useState(false);const cursor=useRef<HTMLDivElement>(null);const heroVisual=useRef<HTMLDivElement>(null);const {scrollYProgress}=useScroll();const progress=useTransform(scrollYProgress,[0,1],["0%","100%"]);
 useEffect(()=>{setIntro(!sessionStorage.getItem("qorvex-intro"));sessionStorage.setItem("qorvex-intro","1");const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const lenis=new Lenis({lerp:.095,smoothWheel:!reduced,wheelMultiplier:.88});let id=0,tx=innerWidth/2,ty=innerHeight/2,cx=tx,cy=ty;const raf=(t:number)=>{lenis.raf(t);cx+=(tx-cx)*.25;cy+=(ty-cy)*.25;if(cursor.current)cursor.current.style.transform=`translate3d(${cx}px,${cy}px,0)`;if(heroVisual.current&&!reduced){const rx=(cy/innerHeight-.5)*-4,ry=(cx/innerWidth-.5)*6;heroVisual.current.style.transform=`translate3d(${ry}px,${rx}px,0) rotateX(${rx}deg) rotateY(${ry}deg)`}id=requestAnimationFrame(raf)};const move=(e:MouseEvent)=>{tx=e.clientX;ty=e.clientY};const over=(e:MouseEvent)=>{const el=(e.target as HTMLElement).closest<HTMLElement>("a,button,article,.case,.feature-row,.process-step,.stats>div,label");cursor.current?.classList.toggle("is-hovering",!!el);cursor.current?.setAttribute("data-label",el?.dataset.cursor||"")};const observer=new IntersectionObserver(es=>es.forEach(e=>e.target.classList.toggle("is-visible",e.isIntersecting)),{rootMargin:"0px 0px -8% 0px",threshold:.08});document.querySelectorAll(".feature-row,.process-step,.services article").forEach(el=>observer.observe(el));window.addEventListener("mousemove",move,{passive:true});document.addEventListener("mouseover",over,{passive:true});id=requestAnimationFrame(raf);return()=>{cancelAnimationFrame(id);lenis.destroy();observer.disconnect();window.removeEventListener("mousemove",move);document.removeEventListener("mouseover",over)}},[]);
 return <>
  <AnimatePresence>{intro&&<motion.div className="intro"><div className="intro-half left"/><div className="intro-half right"/><div className="intro-particles"/><motion.div className="intro-center" initial={{opacity:0}} animate={{opacity:1}}><motion.div className="intro-logo" initial={{scale:.35,rotate:45,opacity:0,filter:"blur(14px)"}} animate={{scale:1,rotate:0,opacity:1,filter:"blur(0)"}} transition={{delay:.25,duration:.8}}><Mark/></motion.div><motion.p initial={{letterSpacing:"1.1em",opacity:0}} animate={{letterSpacing:".42em",opacity:1}} transition={{delay:.8,duration:.8}}>QORVEX</motion.p><motion.span initial={{opacity:0}} animate={{opacity:1}} transition={{delay:1.4}}>BUILDING EXPERIENCE</motion.span><div className="loader"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:1.5,duration:1.25}} onAnimationComplete={()=>setTimeout(()=>setIntro(false),300)}/></div></motion.div></motion.div>}</AnimatePresence>
  <div ref={cursor} className="cursor"/><motion.div className="page-progress" style={{height:progress}}/>
  <main><AmbientScene/><div className="ambient-mesh" aria-hidden="true"><i/><i/><i/></div><div className="site-noise"/><div className="site-grid"/>
   <header className="nav-wrap"><nav className="nav shell"><a className="brand" href="#top"><Mark/><span>QORVEX</span></a><div className="nav-links">{["Work","Services","Process","About","Contact"].map(i=><a key={i} href={`#${i.toLowerCase()}`}>{i}</a>)}</div><a className="nav-cta" href="#contact">Start a project <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button></nav></header>
   <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}}><button onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button>{["Work","Services","Process","About","Contact"].map(i=><a key={i} onClick={()=>setMenu(false)} href={`#${i.toLowerCase()}`}>{i}</a>)}</motion.div>}</AnimatePresence>
   <section className="hero shell cinematic-hero" id="top"><HeroConsole/><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.9}}><p className="eyebrow"><i/> Digital production studio</p><h1>We build digital<br/>experiences that<br/><em>drive growth.</em></h1><p className="lede">From idea and code to campaigns and scale—digital systems engineered for ambitious businesses.</p><div className="hero-actions"><a className="primary magnetic" href="#journey">Enter the system <ArrowDown size={18}/></a><a className="secondary" href="#work">Explore our work <ArrowUpRight size={17}/></a></div></motion.div><div ref={heroVisual} className="hero-visual" aria-hidden="true"><div className="orbit"/><div className="orbit orbit-two"/><div className="sphere"/><div className="core">QX</div><span className="coordinate c1">BUILD / READY</span><span className="coordinate c2">SYSTEM / 01</span></div><div className="hero-foot"><span>Independent digital studio<br/>London · Worldwide</span><span>Scroll controls the story <ArrowDown size={14}/></span></div></section>
   <div className="marquee"><div>{[...tech,...tech].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></div>
   <div id="journey"><CinematicJourney/></div>
   <section className="section shell" id="services"><Reveal><p className="kicker">01 / Departments</p><div className="section-head"><h2>What we <em>build.</em></h2><p>One senior team connecting product engineering, creative production and measurable growth.</p></div></Reveal><div className="services">{services.map((s,i)=><motion.article data-cursor="EXPLORE" key={s[1]} whileHover={{y:-7}}><span>{s[0]}</span><div className="service-icon">{String(i+1).padStart(2,"0")}</div><h3>{s[1]}</h3><p>{s[2]}</p><ArrowUpRight/></motion.article>)}</div></section>
   <FactoryRail/>
   <section className="section work-section" id="work"><div className="shell"><Reveal><p className="kicker">02 / Selected work</p><div className="section-head"><h2>Built for the<br/><em>real world.</em></h2><p>A selection of category-shifting platforms, products and growth systems.</p></div></Reveal>{work.map((w,i)=><Reveal key={w[0]} className="case"><div data-cursor="VIEW" className={`case-visual case-${i+1}`}><span>{w[3]}</span><div className="case-ui"><i/><i/><i/></div></div><div className="case-copy"><p>{w[0]}</p><h3>{w[1]}</h3><span>{w[2]}</span><ArrowUpRight/></div></Reveal>)}</div></section>
   <section className="section shell system-about" id="about"><Reveal><p className="kicker">03 / The company system</p><div className="manifesto"><h2>People + process<br/>+ technology =<br/><em>momentum.</em></h2><p>We combine software engineering, intelligent automation, creative design and performance thinking in one focused team.</p></div></Reveal><div className="stats">{[["50+","Projects"],["25+","Clients"],["10+","Industries"],["99%","Commitment"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><div className="features">{["Strategy First","Modern Technology","Scalable Architecture","Transparent Process","Performance Focused","Long-Term Support"].map((f,i)=><div className="feature-row" key={f}><span>{String(i+1).padStart(2,"0")}</span><h3>{f}</h3><Plus/></div>)}</div></section>
   <section className="section process-section" id="process"><div className="shell"><Reveal><p className="kicker">04 / The process</p><div className="section-head"><h2>A timeline built<br/>for <em>momentum.</em></h2><p>Every stage advances the same system—from an uncertain idea to measurable growth.</p></div></Reveal><div className="process">{process.map(p=><div key={p[0]} className="process-step"><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></div>)}</div></div></section>
   <section className="quote shell"><Reveal><span className="quote-mark">“</span><blockquote>Qorvex took a complex operational challenge and turned it into a product our entire team actually wants to use.</blockquote><p>— ALEX MORGAN, OPERATIONS DIRECTOR</p></Reveal></section>
   <section className="cta final-film"><div className="cta-glow"/><Reveal><p className="kicker">THE SYSTEM IS READY / 100%</p><h2>Let’s build<br/>something worth<br/><em>moving.</em></h2><a className="primary" href="#contact">Start your project <ArrowUpRight/></a></Reveal></section>
   <section className="section contact shell" id="contact"><Reveal className="contact-info"><p className="kicker">05 / Start the build</p><h2>What are we<br/><em>building?</em></h2><p>Choose a direction, then tell us about the ambition behind it.</p><div><a href="mailto:hello@qorvex.com"><Mail/>hello@qorvex.com</a><a href="tel:+440000000000"><Phone/>+44 (0) 000 000 0000</a><span><MapPin/>London · Working worldwide</span></div></Reveal><Reveal><form onSubmit={e=>e.preventDefault()}><fieldset><legend>What are we building?</legend><div className="project-choices">{["Website","Software","Mobile App","Marketing","Something else"].map(x=><label key={x}><input type="radio" name="project"/><span>{x}</span></label>)}</div></fieldset><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Tell us about it<textarea rows={4} placeholder="The opportunity, challenge or outcome..."/></label><button className="primary">Start the build <ArrowRight/></button></form></Reveal></section>
   <footer><div className="shell"><div className="footer-top"><div><a className="brand" href="#top"><Mark/><span>QORVEX</span></a><p>Engineering digital excellence.</p></div><div>{["Work","Services","Process","About","Contact"].map(i=><a key={i} href={`#${i.toLowerCase()}`}>{i}</a>)}</div></div><div className="footer-bottom"><span>© 2026 Qorvex Solutions</span><span>Idea → Code → Product → Growth</span></div></div></footer>
  </main>
 </>
}
