"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion, useScroll, useTransform } from "framer-motion";
import { ArrowDown, ArrowRight, ArrowUpRight, Menu, X, Mail, MapPin, Phone, Plus } from "lucide-react";
import Lenis from "lenis";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const services = [
  ["01","Web Development","Corporate websites, custom platforms and scalable web applications."],
  ["02","Mobile Apps","High-performance Android and iOS experiences built for real users."],
  ["03","SaaS Development","Purpose-built products that turn ambitious ideas into recurring value."],
  ["04","AI Automation","Intelligent agents and workflows that remove friction from your business."],
  ["05","Digital Marketing","Performance campaigns engineered around measurable, sustainable growth."],
  ["06","Brand & Design","Identity, product design and creative systems with a singular point of view."],
  ["07","Cloud & DevOps","Resilient infrastructure, deployment and scalable cloud architecture."],
  ["08","Social Growth","Strategy, content systems and management that build lasting attention."],
];
const work = [
  ["VANTAGE / REAL ESTATE", "A digital property platform built to turn discovery into decision.", "Product design · Development", "01"],
  ["NEXUS / HEALTHCARE", "One connected system for modern clinical operations.", "Strategy · SaaS · Cloud", "02"],
  ["ARC / COMMERCE", "A growth engine that made every interaction measurable.", "Commerce · Performance", "03"],
];
const process = [["01","Discover","We find the real problem, define success and align on direction."],["02","Design","We shape the system, experience and visual language around your ambition."],["03","Develop","We build with modern technology, exacting craft and scalable foundations."],["04","Launch","We test, refine and release with confidence—not crossed fingers."],["05","Scale","We learn from reality, optimize performance and compound what works."]];
const tech = ["NEXT.JS","REACT","NODE.JS","POSTGRESQL","AWS","DOCKER","OPENAI","SHOPIFY","THREE.JS"];

function Mark(){return <span className="brand-mark">QX</span>}
function Reveal({children,className=""}:{children:React.ReactNode,className?:string}){return <motion.div className={className} initial={{opacity:0,y:55,filter:"blur(12px)"}} whileInView={{opacity:1,y:0,filter:"blur(0px)"}} viewport={{once:true,margin:"-12%"}} transition={{duration:.85,ease:[.16,1,.3,1]}}>{children}</motion.div>}

export default function Home(){
  const [intro,setIntro]=useState(false); const [menu,setMenu]=useState(false); const cursor=useRef<HTMLDivElement>(null); const {scrollYProgress}=useScroll(); const progress=useTransform(scrollYProgress,[0,1],["0%","100%"]);
  useEffect(()=>{setIntro(!sessionStorage.getItem("qorvex-intro"));sessionStorage.setItem("qorvex-intro","1"); const lenis=new Lenis({duration:1.15,smoothWheel:true}); let id=0; const raf=(t:number)=>{lenis.raf(t);id=requestAnimationFrame(raf)}; gsap.registerPlugin(ScrollTrigger); const ctx=gsap.context(()=>{gsap.utils.toArray<HTMLElement>(".feature-row").forEach((el)=>gsap.from(el,{scrollTrigger:{trigger:el,start:"top 88%"},x:-40,opacity:0,duration:.8,ease:"power3.out"}))}); const move=(e:MouseEvent)=>{if(cursor.current) gsap.to(cursor.current,{x:e.clientX,y:e.clientY,duration:.22,ease:"power3.out"})}; const over=(e:MouseEvent)=>{if((e.target as HTMLElement).closest("a,button,article,.case,.feature-row,.process-step,.stats>div,label"))cursor.current?.classList.add("is-hovering")}; const out=()=>cursor.current?.classList.remove("is-hovering"); window.addEventListener("mousemove",move);document.addEventListener("mouseover",over);document.addEventListener("mouseout",out);return()=>{cancelAnimationFrame(id);lenis.destroy();ctx.revert();window.removeEventListener("mousemove",move);document.removeEventListener("mouseover",over);document.removeEventListener("mouseout",out)}} ,[]);
  return <>
    <AnimatePresence>{intro&&<motion.div className="intro" exit={{opacity:1}}><div className="intro-half left"/><div className="intro-half right"/><div className="intro-particles"/><motion.div className="intro-center" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:.35}}><motion.div className="intro-logo" initial={{scale:.35,rotate:45,opacity:0,filter:"blur(14px)"}} animate={{scale:1,rotate:0,opacity:1,filter:"blur(0px)"}} transition={{delay:.4,duration:1.05,ease:[.16,1,.3,1]}}><Mark/></motion.div><motion.p initial={{letterSpacing:"1.1em",opacity:0}} animate={{letterSpacing:".42em",opacity:1}} transition={{delay:1.25,duration:1.15}}>QORVEX</motion.p><motion.span initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:2.05,duration:.65}}>SOLUTIONS</motion.span><div className="loader"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{delay:2.3,duration:2.05,ease:[.65,0,.35,1]}} onAnimationComplete={()=>setTimeout(()=>setIntro(false),520)}/></div></motion.div></motion.div>}</AnimatePresence>
    <div ref={cursor} className="cursor"/><motion.div className="page-progress" style={{height:progress}}/>
    <main><div className="site-noise" aria-hidden="true"/><div className="site-grid" aria-hidden="true"/>
      <header className="nav-wrap"><nav className="nav shell"><a className="brand" href="#top"><Mark/><span>QORVEX</span></a><div className="nav-links">{["Services","Work","Process","About","Contact"].map(i=><a key={i} href={`#${i.toLowerCase()}`}>{i}</a>)}</div><a className="nav-cta" href="#contact">Get proposal <ArrowUpRight size={15}/></a><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button></nav></header>
      <AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}}><button onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button>{["Services","Work","Process","About","Contact"].map(i=><a key={i} onClick={()=>setMenu(false)} href={`#${i.toLowerCase()}`}>{i}</a>)}</motion.div>}</AnimatePresence>
      <section className="hero shell" id="top"><motion.div className="hero-copy" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.9}}><p className="eyebrow"><i/> Engineering digital excellence</p><h1>We build digital<br/>experiences that<br/><em>drive growth.</em></h1><p className="lede">Websites, apps, AI solutions and digital systems engineered for ambitious businesses.</p><div className="hero-actions"><a className="primary magnetic" href="#contact">Start a project <ArrowUpRight size={18}/></a><a className="secondary" href="#services">Explore our work <ArrowDown size={17}/></a></div></motion.div><motion.div className="hero-visual" animate={{rotate:[0,3,0,-3,0]}} transition={{duration:12,repeat:Infinity}} aria-hidden="true"><div className="orbit"/><div className="orbit orbit-two"/><div className="sphere"/><div className="core">QX</div><span className="coordinate c1">34.0522° N</span><span className="coordinate c2">SYSTEM / 01</span></motion.div><div className="hero-foot"><span>Independent digital studio<br/>London · Worldwide</span><span>Scroll to explore <ArrowDown size={14}/></span></div></section>
      <div className="marquee"><div>{[...tech,...tech].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></div>

      <section className="section shell" id="services"><Reveal><p className="kicker">01 / Capabilities</p><div className="section-head"><h2>What we <em>build.</em></h2><p>From first principle to final pixel—one senior team for the systems that move your business forward.</p></div></Reveal><div className="services">{services.map((s,i)=><motion.article key={s[1]} whileHover={{y:-8}} transition={{type:"spring",stiffness:250}}><span>{s[0]}</span><div className="service-icon">{String(i+1).padStart(2,"0")}</div><h3>{s[1]}</h3><p>{s[2]}</p><ArrowUpRight/></motion.article>)}</div></section>
      <section className="section work-section" id="work"><div className="shell"><Reveal><p className="kicker">02 / Selected work</p><div className="section-head"><h2>Built for the<br/><em>real world.</em></h2><p>A selection of category-shifting platforms, products and growth systems.</p></div></Reveal>{work.map((w,i)=><Reveal key={w[0]} className="case"><div className={`case-visual case-${i+1}`}><span>{w[3]}</span><div className="case-ui"><i/><i/><i/></div></div><div className="case-copy"><p>{w[0]}</p><h3>{w[1]}</h3><span>{w[2]}</span><ArrowUpRight/></div></Reveal>)}</div></section>
      <section className="section shell" id="about"><Reveal><p className="kicker">03 / Why Qorvex</p><div className="manifesto"><h2>Built for businesses<br/>that want to <em>scale.</em></h2><p>We combine software engineering, intelligent automation, creative design and performance thinking in one focused team.</p></div></Reveal><div className="stats">{[["50+","Projects"],["25+","Clients"],["10+","Industries"],["99%","Commitment"]].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div><div className="features">{["Strategy First","Modern Technology","Scalable Architecture","Transparent Process","Performance Focused","Long-Term Support"].map((f,i)=><div className="feature-row" key={f}><span>{String(i+1).padStart(2,"0")}</span><h3>{f}</h3><Plus/></div>)}</div></section>
      <section className="section process-section" id="process"><div className="shell"><Reveal><p className="kicker">04 / The process</p><div className="section-head"><h2>Clarity at<br/><em>every step.</em></h2><p>No black box. A sharp, collaborative process that keeps momentum visible.</p></div></Reveal><div className="process">{process.map(p=><Reveal key={p[0]} className="process-step"><span>{p[0]}</span><h3>{p[1]}</h3><p>{p[2]}</p></Reveal>)}</div></div></section>
      <section className="quote shell"><Reveal><span className="quote-mark">“</span><blockquote>Qorvex took a complex operational challenge and turned it into a product our entire team actually wants to use.</blockquote><p>— ALEX MORGAN, OPERATIONS DIRECTOR</p></Reveal></section>
      <div className="marquee tech"><div>{[...tech,...tech].map((t,i)=><span key={i}>{t}<b>✦</b></span>)}</div></div>
      <section className="cta"><div className="cta-glow"/><Reveal><p className="kicker">Have an ambitious idea?</p><h2>Ready to build<br/>something <em>exceptional?</em></h2><a className="primary" href="#contact">Start your project <ArrowUpRight/></a></Reveal></section>
      <section className="section contact shell" id="contact"><Reveal className="contact-info"><p className="kicker">05 / Start a conversation</p><h2>Tell us what<br/>you’re <em>building.</em></h2><p>Share a little about your ambition. We’ll reply with thoughtful next steps—not a sales sequence.</p><div><a href="mailto:hello@qorvex.com"><Mail/>hello@qorvex.com</a><a href="tel:+440000000000"><Phone/>+44 (0) 000 000 0000</a><span><MapPin/>London · Working worldwide</span></div></Reveal><Reveal><form onSubmit={e=>e.preventDefault()}><label>Name<input required placeholder="Your name"/></label><label>Email<input required type="email" placeholder="you@company.com"/></label><label>Company<input placeholder="Company name"/></label><div className="form-pair"><label>Project type<select defaultValue=""><option value="" disabled>Select a service</option><option>Website</option><option>Product / SaaS</option><option>AI automation</option><option>Growth & marketing</option></select></label><label>Budget<select defaultValue=""><option value="" disabled>Select range</option><option>£10k – £25k</option><option>£25k – £50k</option><option>£50k+</option></select></label></div><label>Message<textarea rows={4} placeholder="What are you looking to achieve?"/></label><button className="primary">Send enquiry <ArrowRight/></button></form></Reveal></section>
      <footer><div className="shell"><div className="footer-top"><div><a className="brand" href="#top"><Mark/><span>QORVEX</span></a><p>Engineering digital excellence.</p></div><div>{["Services","Work","Process","About","Contact"].map(i=><a key={i} href={`#${i.toLowerCase()}`}>{i}</a>)}</div></div><div className="footer-bottom"><span>© 2026 Qorvex Solutions</span><span>Built with intent. Engineered to last.</span></div></div></footer>
    </main>
  </>
}
